### ISSUE TITLE
incorrect processing internal errors

### ISSUE THREAD

**Issue by mguzelevich** [tropycal/tropycal#190]
```python
        year = 2000
        season = tracks.TrackDataset(
            basin='all',
            source='ibtracs',
            # interpolate_data=True,
            include_btk=True,
            ibtracs_hurdat=True,
        ).get_season(year)
```

raise exception

```
--> Starting to read in ibtracs data
--> Completed reading in ibtracs data (80.52 seconds)
--> Starting to read in HURDAT2 data
Traceback (most recent call last):
  File "main.py", line 89, in <module>
    season = tracks.TrackDataset(
             ^^^^^^^^^^^^^^^^^^^^
  File ".../site-packages/tropycal/tracks/dataset.py", line 234, in __init__
    self.__read_hurdat(override_basin=True)
  File ".../site-packages/tropycal/tracks/dataset.py", line 383, in __read_hurdat
    content = read_hurdat(self.atlantic_url, atl_online)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../site-packages/tropycal/tracks/dataset.py", line 371, in read_hurdat
    f = open(path, "r")
        ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'fetch'
```

**Comment by tomerburg** [comment]
Thanks for opening this issue! This bug was the result of a recent change to automatically fetch the most recent HURDATv2 file off the NHC website, but which was not applied to the IBTrACS setting. This is now fixed in the `develop` branch, and I'll close this issue once the next Tropycal version is released with this fix.
