### ISSUE TITLE
SSL Certificate verification error

### ISSUE THREAD

**Issue by cybertosher** [tropycal/tropycal#215]
I am trying to get realtime plot and keep running into a certificate verification failure. The code I am running is this:

```python
from tropycal import realtime
realtime_obj = realtime.Realtime()
realtime_obj.plot_summary(domain={'w':-100,'e':-10,'s':4,'n':60}, ssl_certificate='/Users/chris/Develop/python/tropy/.venv/lib/python3.12/site-packages/certifi/cacert.pem')
```

I tried without the certificate but that fails too. The stack trace is:

```
--> Starting to read in current storm data
--> Completed reading in current storm data (185.08 seconds)
/Users/chris/Develop/python/tropy/.venv/lib/python3.12/site-packages/tropycal/realtime/realtime.py:766: UserWarning: Error in retrieving NHC invest data.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 1344, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1331, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1377, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1326, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1085, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1029, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1472, in connect
    self.sock = self._context.wrap_socket(self.sock,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 1042, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 1320, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 1535, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/chris/Develop/python/tropy/realtime.py", line 5, in <module>
    realtime_obj.plot_summary(domain={'w':-100,'e':-10,'s':4,'n':60}, save_path='./img', ssl_certificate='/Users/chris/Develop/python/tropy/.venv/lib/python3.12/site-packages/certifi/cacert.pem')
  File "/Users/chris/Develop/python/tropy/.venv/lib/python3.12/site-packages/tropycal/realtime/realtime.py", line 996, in plot_summary
    ax = self.plot_obj.plot_summary([self.get_storm(key) for key in self.storms], self.forecasts,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chris/Develop/python/tropy/.venv/lib/python3.12/site-packages/tropycal/tracks/plot.py", line 2551, in plot_summary
    plt.savefig(save_path, bbox_inches='tight')
  File "/Users/chris/Develop/python/tropy/.venv/lib/python3.12/site-packages/matplotlib/pyplot.py", line 1223, in savefig
    res = fig.savefig(*args, **kwargs)  # type: ignore[func-returns-value]
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chris/Develop/python/tropy/.venv/lib/python3.12/site-packages/matplotlib/figure.py", line 3388, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/Users/chris/Develop/python/tropy/.venv/lib/python3.12/site-packages/matplotlib/backend_bases.py", line 2189, in print_figure
    self.figure.draw(renderer)
  File "/Users/chris/Develop/python/tropy/.venv/lib/python3.12/site-packages/matplotlib/artist.py", line 95, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chris/Develop/python/tropy/.venv/lib/python3.12/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chris/Develop/python/tropy/.venv/lib/python3.12/site-packages/matplotlib/figure.py", line 3155, in draw
    mimage._draw_list_compositing_images(
  File "/Users/chris/Develop/python/tropy/.venv/lib/python3.12/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/Users/chris/Develop/python/tropy/.venv/lib/python3.12/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chris/Develop/python/tropy/.venv/lib/python3.12/site-packages/cartopy/mpl/geoaxes.py", line 525, in draw
    return super().draw(renderer=renderer, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chris/Develop/python/tropy/.venv/lib/python3.12/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chris/Develop/python/tropy/.venv/lib/python3.12/site-packages/matplotlib/axes/_base.py", line 3109, in draw
    mimage._draw_list_compositing_images(
  File "/Users/chris/Develop/python/tropy/.venv/lib/python3.12/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/Users/chris/Develop/python/tropy/.venv/lib/python3.12/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chris/Develop/python/tropy/.venv/lib/python3.12/site-packages/cartopy/mpl/feature_artist.py", line 185, in draw
    geoms = self._feature.intersecting_geometries(extent)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chris/Develop/python/tropy/.venv/lib/python3.12/site-packages/cartopy/feature/__init__.py", line 309, in intersecting_geometries
    return super().intersecting_geometries(extent)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chris/Develop/python/tropy/.venv/lib/python3.12/site-packages/cartopy/feature/__init__.py", line 112, in intersecting_geometries
    return (geom for geom in self.geometries() if
                             ^^^^^^^^^^^^^^^^^
  File "/Users/chris/Develop/python/tropy/.venv/lib/python3.12/site-packages/cartopy/feature/__init__.py", line 291, in geometries
    path = shapereader.natural_earth(resolution=self.scale,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chris/Develop/python/tropy/.venv/lib/python3.12/site-packages/cartopy/io/shapereader.py", line 306, in natural_earth
    return ne_downloader.path(format_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chris/Develop/python/tropy/.venv/lib/python3.12/site-packages/cartopy/io/__init__.py", line 203, in path
    result_path = self.acquire_resource(target_path, format_dict)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chris/Develop/python/tropy/.venv/lib/python3.12/site-packages/cartopy/io/shapereader.py", line 359, in acquire_resource
    shapefile_online = self._urlopen(url)
                       ^^^^^^^^^^^^^^^^^^
  File "/Users/chris/Develop/python/tropy/.venv/lib/python3.12/site-packages/cartopy/io/__init__.py", line 242, in _urlopen
    return urlopen(url)
           ^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 515, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 532, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 1392, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 1347, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)>
```

I looked in a debugger and as far as I can tell the offending URL is:

`https://naturalearth.s3.amazonaws.com/110m_physical/ne_110m_ocean.zip`

This is not the only error. I tried the example to print a summary from 2023 and I get another SSL verification error for a different data file there.

**Comment by cybertosher** [comment]
I was able to find the answer after poking around in a debugger. I was getting SSL verification errors because I did not use the `Install Certificates.command` command on MacOS when I installed Python 3.12. I still do not get a plot that pops up when I run the app, but it does generate the image so I may just be misunderstanding the instructions.
